server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.205.2:3307/yigo?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 106.12.205.2
    port: 6379
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
  rabbitmq:
    host: 106.12.205.2
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
  client:
    serviceUrl:
      defaultZone: http://106.12.205.2:8080/server/eureka/
